# Generated by Django 5.2.7 on 2025-12-11 07:56

import usuarios.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="email",
            field=models.EmailField(
                max_length=254,
                unique=True,
                validators=[usuarios.validators.validar_email_personalizado],
                verbose_name="dirección de correo electrónico",
            ),
        ),
    ]
