# Generated by Django 6.0 on 2025-12-11 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("activos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanMantencion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=255, verbose_name="Nombre del Plan"),
                ),
                (
                    "frecuencia_dias",
                    models.PositiveIntegerField(
                        help_text="Cada cuántos días se debe ejecutar este plan.",
                        verbose_name="Frecuencia (Días)",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="¿Activo?")),
            ],
            options={
                "verbose_name": "Plan de Mantención",
                "verbose_name_plural": "Planes de Mantención",
            },
        ),
        migrations.CreateModel(
            name="OrdenTrabajo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PROGRAMADA", "Programada"),
                            ("EN_PROGRESO", "En Progreso"),
                            ("COMPLETADA", "Completada"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="PROGRAMADA",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "fecha_programada",
                    models.DateTimeField(verbose_name="Fecha Programada"),
                ),
                (
                    "completado_en",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha Completado"
                    ),
                ),
                (
                    "notas",
                    models.TextField(blank=True, verbose_name="Notas/Observaciones"),
                ),
                (
                    "equipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="activos.equipo",
                        verbose_name="Equipo Objetivo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Orden de Trabajo",
                "verbose_name_plural": "Órdenes de Trabajo",
                "ordering": ["-fecha_programada"],
            },
        ),
    ]
