# Generated by Django 6.0 on 2025-12-11 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("activos", "0001_initial"),
        ("operaciones", "0001_initial"),
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordentrabajo",
            name="tecnico",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ordenes_asignadas",
                to="usuarios.tecnico",
                verbose_name="Técnico Asignado",
            ),
        ),
        migrations.AddField(
            model_name="planmantencion",
            name="equipo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="planes_mantencion",
                to="activos.equipo",
                verbose_name="Equipo",
            ),
        ),
        migrations.AddField(
            model_name="ordentrabajo",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ordenes",
                to="operaciones.planmantencion",
                verbose_name="Plan Base",
            ),
        ),
    ]
