# Generated by Django 6.0 on 2025-12-11 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Nombre Empresa"
                    ),
                ),
                ("direccion", models.TextField(verbose_name="Dirección")),
                ("rut", models.CharField(max_length=20, verbose_name="RUT")),
                (
                    "creado_en",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresas",
                "ordering": ["-creado_en"],
            },
        ),
        migrations.CreateModel(
            name="Equipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=255, verbose_name="Nombre del Equipo"),
                ),
                (
                    "numero_serie",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Número de Serie"
                    ),
                ),
                (
                    "es_critico",
                    models.BooleanField(default=False, verbose_name="¿Es Crítico?"),
                ),
                (
                    "fecha_instalacion",
                    models.DateField(verbose_name="Fecha de Instalación"),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipos",
                        to="activos.empresa",
                        verbose_name="Empresa Propietaria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipo",
                "verbose_name_plural": "Equipos",
                "indexes": [
                    models.Index(
                        fields=["empresa", "nombre"],
                        name="activos_equ_empresa_7042e7_idx",
                    )
                ],
            },
        ),
    ]
