# Generated by Django 6.0 on 2025-12-11 05:54

import activos.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empresa",
            name="rut",
            field=models.CharField(
                help_text="Formato: 12.345.678-9 o 12345678-9",
                max_length=20,
                validators=[activos.validators.validar_rut_chileno],
                verbose_name="RUT",
            ),
        ),
    ]
